/** Global drug catalog — 100 medications across 10 categories. */
module.exports = [
  // Analgesics & Antipyretics (10)
  { name: "Paracetamol 500mg", category: "Analgesics & Antipyretics" },
  { name: "Ibuprofen 400mg", category: "Analgesics & Antipyretics" },
  { name: "Aspirin 100mg", category: "Analgesics & Antipyretics" },
  { name: "Diclofenac 50mg", category: "Analgesics & Antipyretics" },
  { name: "Naproxen 250mg", category: "Analgesics & Antipyretics" },
  { name: "Tramadol 50mg", category: "Analgesics & Antipyretics" },
  { name: "Codeine/Paracetamol", category: "Analgesics & Antipyretics" },
  { name: "Meloxicam 15mg", category: "Analgesics & Antipyretics" },
  { name: "Ketoprofen 100mg", category: "Analgesics & Antipyretics" },
  { name: "Piroxicam 20mg", category: "Analgesics & Antipyretics" },

  // Antibiotics (10)
  { name: "Amoxicillin 500mg", category: "Antibiotics" },
  { name: "Azithromycin 250mg", category: "Antibiotics" },
  { name: "Ciprofloxacin 500mg", category: "Antibiotics" },
  { name: "Doxycycline 100mg", category: "Antibiotics" },
  { name: "Metronidazole 400mg", category: "Antibiotics" },
  { name: "Cephalexin 500mg", category: "Antibiotics" },
  { name: "Clarithromycin 500mg", category: "Antibiotics" },
  { name: "Trimethoprim/Sulfamethoxazole", category: "Antibiotics" },
  { name: "Amoxicillin/Clavulanate 625mg", category: "Antibiotics" },
  { name: "Nitrofurantoin 100mg", category: "Antibiotics" },

  // Antihypertensives (10)
  { name: "Amlodipine 5mg", category: "Antihypertensives" },
  { name: "Losartan 50mg", category: "Antihypertensives" },
  { name: "Enalapril 10mg", category: "Antihypertensives" },
  { name: "Metoprolol 50mg", category: "Antihypertensives" },
  { name: "Hydrochlorothiazide 25mg", category: "Antihypertensives" },
  { name: "Valsartan 80mg", category: "Antihypertensives" },
  { name: "Bisoprolol 5mg", category: "Antihypertensives" },
  { name: "Ramipril 5mg", category: "Antihypertensives" },
  { name: "Atenolol 50mg", category: "Antihypertensives" },
  { name: "Candesartan 8mg", category: "Antihypertensives" },

  // Antidiabetics (10)
  { name: "Metformin 500mg", category: "Antidiabetics" },
  { name: "Glibenclamide 5mg", category: "Antidiabetics" },
  { name: "Gliclazide 80mg", category: "Antidiabetics" },
  { name: "Sitagliptin 100mg", category: "Antidiabetics" },
  { name: "Insulin Glargine", category: "Antidiabetics" },
  { name: "Insulin Aspart", category: "Antidiabetics" },
  { name: "Empagliflozin 10mg", category: "Antidiabetics" },
  { name: "Pioglitazone 15mg", category: "Antidiabetics" },
  { name: "Acarbose 50mg", category: "Antidiabetics" },
  { name: "Repaglinide 1mg", category: "Antidiabetics" },

  // Antihistamines (10)
  { name: "Cetirizine 10mg", category: "Antihistamines" },
  { name: "Loratadine 10mg", category: "Antihistamines" },
  { name: "Fexofenadine 120mg", category: "Antihistamines" },
  { name: "Chlorpheniramine 4mg", category: "Antihistamines" },
  { name: "Desloratadine 5mg", category: "Antihistamines" },
  { name: "Levocetirizine 5mg", category: "Antihistamines" },
  { name: "Promethazine 25mg", category: "Antihistamines" },
  { name: "Diphenhydramine 25mg", category: "Antihistamines" },
  { name: "Hydroxyzine 25mg", category: "Antihistamines" },
  { name: "Bilastine 20mg", category: "Antihistamines" },

  // Cardiovascular (10)
  { name: "Atorvastatin 20mg", category: "Cardiovascular" },
  { name: "Simvastatin 20mg", category: "Cardiovascular" },
  { name: "Clopidogrel 75mg", category: "Cardiovascular" },
  { name: "Warfarin 5mg", category: "Cardiovascular" },
  { name: "Rivaroxaban 20mg", category: "Cardiovascular" },
  { name: "Apixaban 5mg", category: "Cardiovascular" },
  { name: "Isosorbide Mononitrate 20mg", category: "Cardiovascular" },
  { name: "Digoxin 0.25mg", category: "Cardiovascular" },
  { name: "Furosemide 40mg", category: "Cardiovascular" },
  { name: "Spironolactone 25mg", category: "Cardiovascular" },

  // Gastrointestinal (10)
  { name: "Omeprazole 20mg", category: "Gastrointestinal" },
  { name: "Pantoprazole 40mg", category: "Gastrointestinal" },
  { name: "Ranitidine 150mg", category: "Gastrointestinal" },
  { name: "Domperidone 10mg", category: "Gastrointestinal" },
  { name: "Metoclopramide 10mg", category: "Gastrointestinal" },
  { name: "Loperamide 2mg", category: "Gastrointestinal" },
  { name: "Bisacodyl 5mg", category: "Gastrointestinal" },
  { name: "Lactulose Syrup", category: "Gastrointestinal" },
  { name: "Simethicone 40mg", category: "Gastrointestinal" },
  { name: "Sucralfate 1g", category: "Gastrointestinal" },

  // Respiratory (10)
  { name: "Salbutamol Inhaler", category: "Respiratory" },
  { name: "Budesonide Inhaler", category: "Respiratory" },
  { name: "Montelukast 10mg", category: "Respiratory" },
  { name: "Theophylline 200mg", category: "Respiratory" },
  { name: "Ambroxol 30mg", category: "Respiratory" },
  { name: "Bromhexine 8mg", category: "Respiratory" },
  { name: "Guaifenesin Syrup", category: "Respiratory" },
  { name: "Dextromethorphan Syrup", category: "Respiratory" },
  { name: "Ipratropium Inhaler", category: "Respiratory" },
  { name: "Fluticasone Nasal Spray", category: "Respiratory" },

  // Vitamins & Supplements (10)
  { name: "Vitamin D3 1000 IU", category: "Vitamins & Supplements" },
  { name: "Vitamin C 500mg", category: "Vitamins & Supplements" },
  { name: "Vitamin B Complex", category: "Vitamins & Supplements" },
  { name: "Calcium + Vitamin D", category: "Vitamins & Supplements" },
  { name: "Iron Ferrous Sulfate 325mg", category: "Vitamins & Supplements" },
  { name: "Folic Acid 5mg", category: "Vitamins & Supplements" },
  { name: "Multivitamin Tablets", category: "Vitamins & Supplements" },
  { name: "Omega-3 Fish Oil", category: "Vitamins & Supplements" },
  { name: "Zinc 50mg", category: "Vitamins & Supplements" },
  { name: "Magnesium 250mg", category: "Vitamins & Supplements" },

  // Dermatological (10)
  { name: "Hydrocortisone Cream 1%", category: "Dermatological" },
  { name: "Clotrimazole Cream 1%", category: "Dermatological" },
  { name: "Mupirocin Ointment 2%", category: "Dermatological" },
  { name: "Betamethasone Cream", category: "Dermatological" },
  { name: "Acyclovir Cream 5%", category: "Dermatological" },
  { name: "Permethrin Cream 5%", category: "Dermatological" },
  { name: "Calamine Lotion", category: "Dermatological" },
  { name: "Fusidic Acid Cream", category: "Dermatological" },
  { name: "Tretinoin Cream 0.05%", category: "Dermatological" },
  { name: "Salicylic Acid Ointment", category: "Dermatological" },
];
