/** Global drug catalog — 100 medications for pharmacy inventory seeding. */
module.exports = [
  { name: "Paracetamol 500mg", category: "Painkiller" },
  { name: "Ibuprofen 400mg", category: "Painkiller" },
  { name: "Amoxicillin 500mg", category: "Antibiotic" },
  { name: "Metformin 850mg", category: "Diabetes" },
  { name: "Aspirin 100mg", category: "Cardiovascular" },
  { name: "Ciprofloxacin 500mg", category: "Antibiotic" },
  { name: "Atorvastatin 20mg", category: "Cholesterol" },
  { name: "Omeprazole 20mg", category: "Gastrointestinal" },
  { name: "Losartan 50mg", category: "Hypertension" },
  { name: "Amlodipine 5mg", category: "Hypertension" },
  { name: "Azithromycin 250mg", category: "Antibiotic" },
  { name: "Metoprolol 50mg", category: "Hypertension" },
  { name: "Simvastatin 20mg", category: "Cholesterol" },
  { name: "Clopidogrel 75mg", category: "Cardiovascular" },
  { name: "Pantoprazole 40mg", category: "Gastrointestinal" },
  { name: "Gabapentin 300mg", category: "Neurology" },
  { name: "Amoxicillin-Clavulanate 1g", category: "Antibiotic" },
  { name: "Levothyroxine 50mcg", category: "Thyroid" },
  { name: "Lisinopril 10mg", category: "Hypertension" },
  { name: "Sitagliptin 100mg", category: "Diabetes" },
  { name: "Gliclazide 60mg", category: "Diabetes" },
  { name: "Valsartan 80mg", category: "Hypertension" },
  { name: "Esomeprazole 40mg", category: "Gastrointestinal" },
  { name: "Diclofenac Sodium 50mg", category: "Painkiller" },
  { name: "Meloxicam 15mg", category: "Painkiller" },
  { name: "Tramadol 50mg", category: "Painkiller" },
  { name: "Cephalexin 500mg", category: "Antibiotic" },
  { name: "Doxycycline 100mg", category: "Antibiotic" },
  { name: "Clarithromycin 500mg", category: "Antibiotic" },
  { name: "Fluconazole 150mg", category: "Antifungal" },
  { name: "Prednisolone 5mg", category: "Corticosteroid" },
  { name: "Dexamethasone 4mg", category: "Corticosteroid" },
  { name: "Montelukast 10mg", category: "Respiratory" },
  { name: "Salbutamol Inhaler 100mcg", category: "Respiratory" },
  { name: "Fluticasone Spray", category: "Respiratory" },
  { name: "Cetirizine 10mg", category: "Antihistamine" },
  { name: "Loratadine 10mg", category: "Antihistamine" },
  { name: "Fexofenadine 120mg", category: "Antihistamine" },
  { name: "Ranitidine 150mg", category: "Gastrointestinal" },
  { name: "Domperidone 10mg", category: "Gastrointestinal" },
  { name: "Metoclopramide 10mg", category: "Gastrointestinal" },
  { name: "Hyoscine Butylbromide 10mg", category: "Antispasmodic" },
  { name: "Mebeverine 135mg", category: "Antispasmodic" },
  { name: "Bisoprolol 5mg", category: "Hypertension" },
  { name: "Carvedilol 6.25mg", category: "Hypertension" },
  { name: "Spironolactone 25mg", category: "Cardiovascular" },
  { name: "Furosemide 40mg", category: "Diuretic" },
  { name: "Hydrochlorothiazide 25mg", category: "Diuretic" },
  { name: "Rosuvastatin 10mg", category: "Cholesterol" },
  { name: "Fenofibrate 160mg", category: "Cholesterol" },
  { name: "Empagliflozin 10mg", category: "Diabetes" },
  { name: "Dapagliflozin 10mg", category: "Diabetes" },
  { name: "Pioglitazone 30mg", category: "Diabetes" },
  { name: "Glimepiride 2mg", category: "Diabetes" },
  { name: "Insulin Glargine 100 U/mL", category: "Diabetes" },
  { name: "Alprazolam 0.5mg", category: "Psychiatric" },
  { name: "Diazepam 5mg", category: "Psychiatric" },
  { name: "Clonazepam 2mg", category: "Psychiatric" },
  { name: "Sertraline 50mg", category: "Psychiatric" },
  { name: "Escitalopram 10mg", category: "Psychiatric" },
  { name: "Fluoxetine 20mg", category: "Psychiatric" },
  { name: "Amitriptyline 25mg", category: "Psychiatric" },
  { name: "Olanzapine 5mg", category: "Psychiatric" },
  { name: "Risperidone 2mg", category: "Psychiatric" },
  { name: "Levetiracetam 500mg", category: "Neurology" },
  { name: "Valproate Sodium 500mg", category: "Neurology" },
  { name: "Carbamazepine 200mg", category: "Neurology" },
  { name: "Pregabalin 75mg", category: "Neurology" },
  { name: "Allopurinol 100mg", category: "Gout" },
  { name: "Colchicine 0.5mg", category: "Gout" },
  { name: "Finasteride 5mg", category: "Urology" },
  { name: "Tamsulosin 0.4mg", category: "Urology" },
  { name: "Sildenafil 50mg", category: "Urology" },
  { name: "Acyclovir 400mg", category: "Antiviral" },
  { name: "Oseltamivir 75mg", category: "Antiviral" },
  { name: "Leflunomide 20mg", category: "Rheumatology" },
  { name: "Methotrexate 2.5mg", category: "Rheumatology" },
  { name: "Calcium Carbonate 500mg", category: "Supplements" },
  { name: "Vitamin D3 5000 IU", category: "Supplements" },
  { name: "Ferrous Sulfate 200mg", category: "Supplements" },
  { name: "Folic Acid 5mg", category: "Supplements" },
  { name: "B-Complex Vitamin", category: "Supplements" },
  { name: "Warfarin 5mg", category: "Anticoagulant" },
  { name: "Rivaroxaban 15mg", category: "Anticoagulant" },
  { name: "Enoxaparin 40mg/0.4mL", category: "Anticoagulant" },
  { name: "Hydrocortisone Cream 1%", category: "Dermatology" },
  { name: "Fusidic Acid Cream 2%", category: "Dermatology" },
  { name: "Betamethasone Valerate", category: "Dermatology" },
  { name: "Clotrimazole Cream 1%", category: "Dermatology" },
  { name: "Permethrin Lotion 5%", category: "Dermatology" },
  { name: "Latanoprost Drops", category: "Ophthalmology" },
  { name: "Timolol Maleate Drops", category: "Ophthalmology" },
  { name: "Tobramycin Eye Drops", category: "Ophthalmology" },
  { name: "Sodium Chloride Nasal Spray", category: "Respiratory" },
  { name: "Glycerin Suppository", category: "Gastrointestinal" },
  { name: "Bisacodyl 5mg", category: "Gastrointestinal" },
  { name: "Loperamide 2mg", category: "Gastrointestinal" },
  { name: "Activated Charcoal", category: "Gastrointestinal" },
  { name: "Oral Rehydration Salts", category: "Supplements" },
  { name: "Paracetamol 250mg Suppository", category: "Painkiller" },
];
